### ISSUE TITLE
Iottimeseries problem with authorization

### ISSUE THREAD

**Issue by PetrDvoracek** [PetrDvoracek/django-basic#13]
@antongavlas  will contact Siemens, please add the JSON message

**Comment by antongavlas** [comment]
```json
{
    "timestamp": "2019-03-07T09:01:10.490+0000",
    "status": 401,
    "error": "Unauthorized",
    "exception": "org.springframework.security.access.AccessDeniedException",
    "message": "Insufficient scope for this resource",
    "path": "/api/iottimeseries/v3/timeseries/7f03ff1dc93941e69c09dfc63389d43e/One-1"
}
```

**Comment by PetrDvoracek** [comment]
There is the HTTP communication:
```json
GET /api/iottimeseries/v3/timeseries/7f03ff1dc93941e69c09dfc63389d43e/One HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: gateway.eu1.mindsphere.io
User-Agent: HTTPie/0.9.8
authorization: Bearer {token}



HTTP/1.1 401 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-cache, max-age=0, must-revalidate
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Date: Thu, 07 Mar 2019 09:05:06 GMT
Expires: 0
Expires: 0
Pragma: no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Transfer-Encoding: chunked
X-Application-Context: mindgate:prod:9090
X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block

{
    "error": "Unauthorized", 
    "exception": "org.springframework.security.access.AccessDeniedException", 
    "message": "Insufficient scope for this resource", 
    "path": "/api/iottimeseries/v3/timeseries/7f03ff1dc93941e69c09dfc63389d43e/One", 
    "status": 401, 
    "timestamp": "2019-03-07T09:05:06.712+0000"
}
```

**Comment by PetrDvoracek** [comment]
The token should be ok, no problem to get data from `/api/assetmanagement/v3/assets`

**Comment by PetrDvoracek** [comment]
We used this part of documentation about [timeseries api](https://developer.mindsphere.io/apis/iot-iottimeseries/api-iottimeseries-api-swagger-3-3-0.html).

**Comment by PetrDvoracek** [comment]
It seems like the documentation [1](https://developer.mindsphere.io/apis/iot-iottimeseries/api-iottimeseries-api-swagger-3-3-0.html) differs from [2](https://developer.mindsphere.io/apis/iot-iottimeseries/api-iottimeseries-samples.html). 
Focus on **https://gateway.{region}-{environment}.mindsphere.io/api/iottimeseries/v3/timeseries/{assetId}/{aspectName}**
and 
**/api/iottimeseries/v3/timeseries/{entity}/{propertysetname}**
Is following statement true?
```
{assetId} == {entity} && {aspectName} == {propertysetname}
```

**Comment by zdenek-jelinek** [comment]
If you parse the JWT token (https://jwt.io/), inspecting the body, the "scopes" property should contain "mdsp:core:iot.timUser" or "mdsp:core:iot.timAdmin" to access IoT Timeseries API.

To resolve this, more information on how the token is acquired is necessary from your side. The most probable cause is that your application does not have the required scopes assigned.

You may need to log out and log in again in order for the changes to application scopes in the token to take effect.

**Comment by antongavlas** [comment]
We had a problem with roles (access IoT Timeseries API). At this moment It is working! 👍

**Comment by PetrDvoracek** [comment]
Mindsphere -> DevCockpit -> Authorization Management -> App Roles: select application; Add Core Role - Here you should be able to find any role in Minsphere API, so add it. This should solve the problem.
![Mindsphere](https://user-images.githubusercontent.com/24353175/54110051-a6b31400-43e0-11e9-94cc-1b4cb4f8b71a.PNG)
